package models

import "time"

// ==================== ENUMS ====================

type InviteStatus string

const (
	InviteStatusActive   InviteStatus = "active"
	InviteStatusExpired  InviteStatus = "expired"
	InviteStatusRevoked  InviteStatus = "revoked"
	InviteStatusExhausted InviteStatus = "exhausted" // used_count >= max_uses
)

// ==================== MODEL ====================

// FlatInvite represents a time-bound, usage-controlled invite token
// generated by an admin or primary resident for a specific flat.
//
// Flow:
//   - Admin creates invite → token sent via SMS/deep-link → resident redeems it
//   - On redemption: used_count++, user is created with role=resident/family/guard
//   - If created_by is admin and auto_activate=true → user status=active immediately
//   - If created_by is primary resident → family member, auto-activated
//   - Open QR registrations do NOT use this table; they go through flat_claim_requests
type FlatInvite struct {
	ID        int64     `db:"id"         json:"id"`
	FlatID    int64     `db:"flat_id"    json:"flat_id"`
	Token     string    `db:"token"      json:"-"` // never expose raw token in list responses
	CreatedBy int64     `db:"created_by" json:"created_by"`
	MaxUses   *int      `db:"max_uses"   json:"max_uses"`   // nil = unlimited
	UsedCount int       `db:"used_count" json:"used_count"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	IsRevoked bool      `db:"is_revoked" json:"is_revoked"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

// ==================== DERIVED HELPERS ====================

// IsValid returns true if the invite can still be redeemed right now.
func (i *FlatInvite) IsValid() bool {
	if i.IsRevoked {
		return false
	}
	if time.Now().After(i.ExpiresAt) {
		return false
	}
	if i.MaxUses != nil && i.UsedCount >= *i.MaxUses {
		return false
	}
	return true
}

// Status derives a human-readable status for API responses.
func (i *FlatInvite) Status() InviteStatus {
	if i.IsRevoked {
		return InviteStatusRevoked
	}
	if time.Now().After(i.ExpiresAt) {
		return InviteStatusExpired
	}
	if i.MaxUses != nil && i.UsedCount >= *i.MaxUses {
		return InviteStatusExhausted
	}
	return InviteStatusActive
}

// RemainingUses returns how many more times this invite can be used.
// Returns nil when unlimited.
func (i *FlatInvite) RemainingUses() *int {
	if i.MaxUses == nil {
		return nil
	}
	remaining := *i.MaxUses - i.UsedCount
	return &remaining
}