package inviteservice

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"net/http"
	"time"

	"go-server/internal/models"
	"go-server/internal/repository"
	"go-server/internal/service"
)

// ==================== CONSTANTS ====================

const (
	tokenByteLength = 32              // 32 random bytes → 64-char hex string (well under VARCHAR(128))
	maxTokenRetries = 3               // retry on the astronomically rare token collision
	defaultTTL      = 72 * time.Hour  // invite valid for 72 hours by default
	defaultMaxUses  = 1               // single-use by default (admin invite for one resident)
)

// ==================== SENTINEL ERRORS ====================

var (
	ErrUnauthorizedInviteCreation = errors.New("only admins or primary residents can create invites")
	ErrInviteInvalid              = errors.New("invite is invalid")
)

// ==================== DTOs ====================

// CreateInviteRequest carries everything needed to mint a new invite.
type CreateInviteRequest struct {
	FlatID    int64
	SocietyID int64 // used for cross-society guard
	CreatedBy int64 // userID of the actor (admin or primary resident)

	// Optional overrides — service applies safe defaults when nil.
	MaxUses   *int          // nil = single-use
	ExpiresIn *time.Duration // nil = defaultTTL
}

// InviteResponse is the outward-facing shape returned after creation.
// The raw token is only exposed here — never in list/get responses.
type InviteResponse struct {
	Invite    *models.FlatInvite
	RawToken  string // send this to the invitee via SMS / deep-link
	DeepLink  string // e.g. myapp://join?token=<raw>
}

// RedeemResult carries everything the caller needs after a successful redemption.
type RedeemResult struct {
	Invite    *models.FlatInvite
	FlatID    int64
	AutoActivate bool // true → caller should set user.status = active immediately
}

// ==================== INTERFACE ====================

type InviteService interface {
	// CreateInvite mints a new, secure invite token for a flat.
	// Validates that the flat belongs to the given society before creating.
	CreateInvite(ctx context.Context, req CreateInviteRequest) (*InviteResponse, error)

	// ValidateAndRedeemToken validates the token and atomically increments used_count.
	// Returns RedeemResult so the caller knows whether to auto-activate the user.
	// Must be called inside a transaction wrapping user creation.
	ValidateAndRedeemToken(ctx context.Context, token string) (*RedeemResult, error)

	// RevokeInvite allows an admin to manually invalidate a specific invite.
	RevokeInvite(ctx context.Context, inviteID int64, actorID int64) error

	// RevokeAllForFlat bulk-revokes every active invite for a flat.
	// Call this when a flat claim is approved to prevent stale tokens being reused.
	RevokeAllForFlat(ctx context.Context, flatID int64) error

	// GetActiveInvitesForFlat returns all non-revoked invites for a flat (admin view).
	GetActiveInvitesForFlat(ctx context.Context, flatID int64, societyID int64) ([]*models.FlatInvite, error)

	// GetInvitesByCreator returns all invites generated by a specific user.
	GetInvitesByCreator(ctx context.Context, createdBy int64) ([]*models.FlatInvite, error)
}

// ==================== IMPLEMENTATION ====================

type inviteService struct {
	inviteRepo repository.InviteRepository
	flatRepo   repository.FlatRepository
	deepLinkFn func(token string) string // injectable so tests don't need a real base URL
}

type Option func(*inviteService)

func WithDeepLinkFn(fn func(token string) string) Option {
	return func(s *inviteService) { s.deepLinkFn = fn }
}

func NewInviteService(
	inviteRepo repository.InviteRepository,
	flatRepo repository.FlatRepository,
	opts ...Option,
) InviteService {
	s := &inviteService{
		inviteRepo: inviteRepo,
		flatRepo:   flatRepo,
		deepLinkFn: func(token string) string {
			return fmt.Sprintf("myapp://join?token=%s", token)
		},
	}
	for _, o := range opts {
		o(s)
	}
	return s
}

// ==================== METHODS ====================

// CreateInvite validates preconditions then mints a cryptographically secure token.
//
// Token collision is handled with up to maxTokenRetries retries.
// The raw token is returned once — store it server-side only if you need resend;
// otherwise treat it as write-once.
func (s *inviteService) CreateInvite(ctx context.Context, req CreateInviteRequest) (*InviteResponse, error) {
	ctx, cancel := context.WithTimeout(ctx, service.DefaultTimeout)
	defer cancel()
	// Guard 1: flat must belong to the claimed society (prevent cross-society abuse)
	flat, err := s.flatRepo.GetFlatByID(ctx, req.FlatID)
	if err != nil {
		if errors.Is(err, repository.ErrFlatNotFound) {
			return nil, repository.ErrFlatNotFound
		}
		return nil, fmt.Errorf("inviteservice: fetch flat for invite: %w", err)
	}
	if flat.SocietyID != req.SocietyID {
		return nil, fmt.Errorf("inviteservice: %w", repository.ErrFlatNotFound) // don't leak existence
	}

	// Guard 2: flat must be active — you cannot invite someone to an inactive flat
	if flat.Status != models.FlatStatusActive {
		return nil, models.NewAppError(
			models.ErrCodeBadRequest,
			"cannot create an invite for an inactive flat",
			http.StatusBadRequest,
			nil,
		)
	}

	// Apply defaults
	maxUses := defaultMaxUses
	if req.MaxUses != nil {
		maxUses = *req.MaxUses
	}
	ttl := defaultTTL
	if req.ExpiresIn != nil {
		ttl = *req.ExpiresIn
	}

	// Mint token with collision retry
	var (
		created  *models.FlatInvite
		rawToken string
	)
	for range maxTokenRetries {
		rawToken, err = generateToken()
		if err != nil {
			return nil, fmt.Errorf("inviteservice: generate token: %w", err)
		}

		invite := &models.FlatInvite{
			FlatID:    req.FlatID,
			Token:     rawToken,
			CreatedBy: req.CreatedBy,
			MaxUses:   &maxUses,
			ExpiresAt: time.Now().UTC().Add(ttl),
		}

		created, err = s.inviteRepo.CreateInvite(ctx, invite)
		if err == nil {
			break // success
		}
		if errors.Is(err, repository.ErrInviteAlreadyExists) {
			continue // token collision → retry
		}
		return nil, fmt.Errorf("inviteservice: persist invite: %w", err)
	}
	if created == nil {
		return nil, fmt.Errorf("inviteservice: failed to create unique token after %d attempts", maxTokenRetries)
	}

	return &InviteResponse{
		Invite:   created,
		RawToken: rawToken,
		DeepLink: s.deepLinkFn(rawToken),
	}, nil
}

// ValidateAndRedeemToken is the hot-path called when a user taps an invite link.
//
// Validation order (fail-fast, cheapest first):
//  1. Token exists in DB
//  2. Not revoked
//  3. Not expired
//  4. Not exhausted (used_count < max_uses)
//  5. Atomic increment of used_count
//
// The caller MUST wrap this call and the subsequent user-creation in a single
// DB transaction (pass it via ctx using your existing GetExecutor pattern)
// so that a failed user insert automatically rolls back the used_count increment.
func (s *inviteService) ValidateAndRedeemToken(ctx context.Context, token string) (*RedeemResult, error) {
	ctx, cancel := context.WithTimeout(ctx, service.DefaultTimeout)
	defer cancel()
	invite, err := s.inviteRepo.GetInviteByToken(ctx, token)
	if err != nil {
		if errors.Is(err, repository.ErrInviteNotFound) {
			// Return a generic error — don't confirm whether the token ever existed
			return nil, ErrInviteInvalid
		}
		return nil, fmt.Errorf("inviteservice: lookup token: %w", err)
	}

	// Validate state in memory (no extra DB round-trips)
	if invite.IsRevoked {
		return nil, repository.ErrInviteRevoked
	}
	if time.Now().After(invite.ExpiresAt) {
		return nil, repository.ErrInviteExpired
	}
	if invite.MaxUses != nil && invite.UsedCount >= *invite.MaxUses {
		return nil, repository.ErrInviteExhausted
	}

	// Atomic increment — if two requests race here, DB CHECK constraint
	// (used_count <= max_uses) will reject the second one at the DB level.
	if err := s.inviteRepo.IncrementUsedCount(ctx, invite.ID); err != nil {
		return nil, fmt.Errorf("inviteservice: redeem token: %w", err)
	}

	// Re-fetch so the returned invite reflects the new used_count.
	// Small overhead but gives the caller accurate state.
	updated, err := s.inviteRepo.GetInviteByID(ctx, invite.ID)
	if err != nil {
		return nil, fmt.Errorf("inviteservice: re-fetch after redeem: %w", err)
	}

	// AutoActivate = true when invite was created by admin/super_admin.
	// The caller resolves the creator's role and passes it to user creation.
	// Here we encode the policy: single-use admin invites auto-activate;
	// multi-use family invites created by primary residents also auto-activate.
	// Open QR flows never touch this service at all.
	autoActivate := !invite.IsRevoked // always true at this point, caller checks role separately

	return &RedeemResult{
		Invite:       updated,
		FlatID:       invite.FlatID,
		AutoActivate: autoActivate,
	}, nil
}

// RevokeInvite soft-deletes a single invite.
// Any role that can see the invite (admin, or the original creator) may revoke it.
func (s *inviteService) RevokeInvite(ctx context.Context, inviteID int64, actorID int64) error {
	ctx, cancel := context.WithTimeout(ctx, service.DefaultTimeout)
	defer cancel()
	invite, err := s.inviteRepo.GetInviteByID(ctx, inviteID)
	if err != nil {
		return fmt.Errorf("inviteservice: fetch invite for revoke: %w", err)
	}

	// Policy: only the creator or an admin (enforced at handler layer) can revoke.
	// We surface the invite so the handler can check invite.CreatedBy == actorID.
	_ = invite // handler owns the authz check; service owns the mutation

	if err := s.inviteRepo.RevokeInvite(ctx, inviteID); err != nil {
		return fmt.Errorf("inviteservice: revoke invite: %w", err)
	}
	return nil
}

// RevokeAllForFlat bulk-revokes every active invite for a flat.
// Call this inside the flat-claim approval transaction so no orphan tokens remain.
func (s *inviteService) RevokeAllForFlat(ctx context.Context, flatID int64) error {
	ctx, cancel := context.WithTimeout(ctx, service.DefaultTimeout)
	defer cancel()
	if err := s.inviteRepo.RevokeAllInvitesByFlat(ctx, flatID); err != nil {
		return fmt.Errorf("inviteservice: revoke all invites for flat: %w", err)
	}
	return nil
}

// GetActiveInvitesForFlat lists open invites for a flat with society guard.
func (s *inviteService) GetActiveInvitesForFlat(ctx context.Context, flatID int64, societyID int64) ([]*models.FlatInvite, error) {
	ctx, cancel := context.WithTimeout(ctx, service.DefaultTimeout)
	defer cancel()
	flat, err := s.flatRepo.GetFlatByID(ctx, flatID)
	if err != nil {
		return nil, fmt.Errorf("inviteservice: fetch flat: %w", err)
	}
	if flat.SocietyID != societyID {
		return nil, repository.ErrFlatNotFound // don't leak cross-society data
	}

	invites, err := s.inviteRepo.GetActiveInvitesByFlat(ctx, flatID)
	if err != nil {
		return nil, fmt.Errorf("inviteservice: get active invites: %w", err)
	}
	// Scrub the raw token from list responses — only expose on creation.
	for _, inv := range invites {
		inv.Token = ""
	}
	return invites, nil
}

// GetInvitesByCreator returns all invites generated by a user.
func (s *inviteService) GetInvitesByCreator(ctx context.Context, createdBy int64) ([]*models.FlatInvite, error) {
	ctx, cancel := context.WithTimeout(ctx, service.DefaultTimeout)
	defer cancel()
	invites, err := s.inviteRepo.GetInvitesByCreator(ctx, createdBy)
	if err != nil {
		return nil, fmt.Errorf("inviteservice: get invites by creator: %w", err)
	}
	for _, inv := range invites {
		inv.Token = "" // scrub
	}
	return invites, nil
}

// ==================== HELPERS ====================

// generateToken produces a cryptographically secure random hex string.
// 32 bytes → 256 bits of entropy → collision probability negligible.
func generateToken() (string, error) {
	b := make([]byte, tokenByteLength)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("inviteservice: read random bytes: %w", err)
	}
	return hex.EncodeToString(b), nil
}