package onboardingservice

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"go-server/internal/models"
	"go-server/internal/repository"
	"go-server/internal/service"
	inviteservice "go-server/internal/service/invite_service"
	planservice "go-server/internal/service/plan_service"
	"go-server/pkg/utils"
)

// ==================== ROLE CONSTANTS ====================

const (
	RolePrimaryResident = "user"   // matches users.role CHECK constraint
	RoleAdmin           = "admin"
	RoleSuperAdmin      = "super_admin"
	RoleStaff           = "staff"
)

// ==================== SENTINEL ERRORS ====================

var (
	ErrFlatAlreadyOccupied   = errors.New("flat already has a primary resident")
	ErrNotSocietyMember      = errors.New("user does not belong to this society")
	ErrDuplicatePendingClaim = errors.New("you already have a pending claim for this flat")
	ErrClaimNotFound         = errors.New("claim request not found")
	ErrClaimNotPending       = errors.New("claim is no longer pending")
	ErrFlatSocietyMismatch   = errors.New("flat does not belong to this society")
	ErrUserAlreadyAssigned   = errors.New("user is already assigned to a flat")
)

// ==================== INTERFACE ====================

// OnboardingService orchestrates the two resident-onboarding paths:
//
//  1. QR / self-service: resident scans the society QR, signs up, picks their
//     flat, and submits a FlatClaimRequest (always pending → admin approval
//     required before the user is activated).
//
//  2. Invite: admin (or primary resident for family members) pre-generates a
//     time-bound token for a specific flat. When a user redeems the token they
//     are immediately assigned to the flat and auto-activated (trust is implied
//     because the invite was generated by a trusted actor).
type OnboardingService interface {
	// --- Registration (no OTP) ---

	// RegisterResident creates a new user account that is immediately verified
	// (is_verified = true). No OTP is sent or required. Trust is established
	// either by the subsequent admin-approval of a flat claim, or by redeeming
	// a pre-generated invite token.
	RegisterResident(ctx context.Context, req *models.RegisterRequest) (*models.User, error)

	// RegisterStaff creates a new staff account that is immediately verified.
	// This is a separate method with role = staff because staff users don't go through the flat claim or invite flow and don't need society/flat assignments.
	// Only admins can create staff accounts, and staff users have a different set of permissions (e.g. can manage societies but not users or flats).
	RegisterStaff(ctx context.Context, req *models.RegisterRequest, societyID int64) (*models.User, error)

	// --- QR / self-service path ---

	// GetSocietyFlats returns the flat list for a society identified by its
	// human-readable SocietyCode. Called during QR scanning before the resident
	// is even logged in (no societyID in JWT yet).
	GetSocietyFlatsByCode(ctx context.Context, societyCode string) ([]*models.Flat, error)

	// SubmitClaim creates a pending FlatClaimRequest for the authenticated user.
	// Validates: flat belongs to society, flat has no primary resident yet,
	// no duplicate pending claim exists.
	SubmitClaim(ctx context.Context, req *models.SubmitClaimRequest) (*models.FlatClaimRequest, error)

	// ApproveClaim approves a pending claim and:
	//   - sets user.flat_id, user.society_id, user.role = primary resident
	//   - marks flat as active (occupied)
	//   - revokes all other pending invites for the same flat
	// All mutations execute in one transaction.
	ApproveClaim(ctx context.Context, req *models.ReviewClaimRequest) (*models.OnboardingResult, error)

	// RejectClaim rejects a pending claim with an optional reason.
	RejectClaim(ctx context.Context, req *models.ReviewClaimRequest) (*models.FlatClaimRequest, error)

	// --- Invite path ---

	// CreateInvite mints a new signed token for a specific flat.
	// The actor must be an admin of the society or the primary resident of the flat.
	CreateInvite(ctx context.Context, req inviteservice.CreateInviteRequest) (*inviteservice.InviteResponse, error)

	// RedeemInvite validates the token and immediately assigns the user to the flat.
	// The role assigned depends on context (admin-issued → user, invite by resident → user).
	// The user is auto-activated; no admin approval is needed.
	RedeemInvite(ctx context.Context, req *models.RedeemInviteRequest) (*models.OnboardingResult, error)

	// --- Admin / read-only views ---

	// ListPendingClaims returns all pending claim requests in a society.
	ListPendingClaims(ctx context.Context, societyID int64) ([]*models.FlatClaimRequest, error)

	// ListAllClaims returns claims filtered by optional status.
	ListAllClaims(ctx context.Context, societyID int64, status *models.ClaimStatus) ([]*models.FlatClaimRequest, error)

	// GetMyClaimHistory returns all claim requests submitted by the calling user.
	GetMyClaimHistory(ctx context.Context, userID int64) ([]*models.FlatClaimRequest, error)

	// GetActiveInvitesForFlat returns non-revoked invites for a flat (admin view).
	GetActiveInvitesForFlat(ctx context.Context, flatID int64, societyID int64) ([]*models.FlatInvite, error)

	// RevokeInvite allows an admin or the invite creator to revoke a single invite.
	RevokeInvite(ctx context.Context, inviteID int64, actorID int64) error
}

// ==================== IMPLEMENTATION ====================

type onboardingService struct {
	userRepo     repository.UserRepository
	flatRepo     repository.FlatRepository
	societyRepo  repository.SocietyRepository
	claimRepo    repository.ClaimRepository
	inviteRepo   repository.InviteRepository
	inviteSvc    inviteservice.InviteService
	txManager    repository.TransactionManager
	planSvc      planservice.PlanService
}

func NewOnboardingService(
	userRepo repository.UserRepository,
	flatRepo repository.FlatRepository,
	societyRepo repository.SocietyRepository,
	claimRepo repository.ClaimRepository,
	inviteRepo repository.InviteRepository,
	inviteSvc inviteservice.InviteService,
	txManager repository.TransactionManager,
	planSvc planservice.PlanService,
) OnboardingService {
	return &onboardingService{
		userRepo:    userRepo,
		flatRepo:    flatRepo,
		societyRepo: societyRepo,
		claimRepo:   claimRepo,
		inviteRepo:  inviteRepo,
		inviteSvc:   inviteSvc,
		txManager:   txManager,
		planSvc:     planSvc,
	}
}

// ==================== REGISTRATION (NO OTP) ====================

// RegisterResident creates a resident account without sending OTP.
// is_verified is set to true immediately because the trust mechanism is either:
//   - admin review of the subsequent flat claim request, OR
//   - the invite token itself (cryptographically bound to a specific flat).
//
// Duplicate email/phone are rejected normally.
func (s *onboardingService) RegisterResident(ctx context.Context, req *models.RegisterRequest) (*models.User, error) {
	ctx, cancel := context.WithTimeout(ctx, service.DefaultTimeout)
	defer cancel()

	req.Name = strings.TrimSpace(req.Name)
	req.Email = strings.TrimSpace(strings.ToLower(req.Email))

	// Duplicate email check
	emailExists, err := s.userRepo.EmailExists(ctx, req.Email)
	if err != nil {
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to check email existence", http.StatusInternalServerError, err)
	}
	if emailExists {
		return nil, models.NewAppError(models.ErrCodeConflict, req.Email+" is already registered", http.StatusConflict, nil)
	}

	// Duplicate phone check
	phoneExists, err := s.userRepo.PhoneExists(ctx, req.PhoneNumber)
	if err != nil {
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to check phone existence", http.StatusInternalServerError, err)
	}
	if phoneExists {
		return nil, models.NewAppError(models.ErrCodeConflict, "phone number is already registered", http.StatusConflict, nil)
	}

	hashedPassword, err := utils.HashPassword(req.Password)
	if err != nil {
		return nil, models.NewAppError(models.ErrCodeInternalServer, "failed to hash password", http.StatusInternalServerError, err)
	}

	user := &models.User{
		Name:         req.Name,
		Email:        req.Email,
		PhoneNumber:  req.PhoneNumber,
		PasswordHash: hashedPassword,
		Role:         "user",
		IsVerified:   true, // skip OTP — trust comes from claim approval or invite token
	}

	if err := s.userRepo.Create(ctx, user); err != nil {
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to create user", http.StatusInternalServerError, err)
	}

	return user, nil
}

func (s *onboardingService) RegisterStaff(ctx context.Context, req *models.RegisterRequest, societyID int64) (*models.User, error) {
	ctx, cancel := context.WithTimeout(ctx, service.DefaultTimeout)
	defer cancel()

	// Check if society can add more staff
	canAdd, err := s.planSvc.CanAddStaff(ctx, societyID)
	if err != nil {
		return nil, err
	}
	if !canAdd {
		return nil, models.NewAppError(models.ErrCodeForbidden, "staff limit reached for the current plan", http.StatusForbidden, nil)
	}

	req.Name = strings.TrimSpace(req.Name)
	req.Email = strings.TrimSpace(strings.ToLower(req.Email))
	// Duplicate email check
	emailExists, err := s.userRepo.EmailExists(ctx, req.Email)
	if err != nil {
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to check email existence", http.StatusInternalServerError, err)
	}
	if emailExists {
		return nil, models.NewAppError(models.ErrCodeConflict, req.Email+" is already registered", http.StatusConflict, nil)
	}
	hashedPassword, err := utils.HashPassword(req.Password)
	if err != nil {
		return nil, models.NewAppError(models.ErrCodeInternalServer, "failed to hash password", http.StatusInternalServerError, err)
	}
	user := &models.User{
		Name:         req.Name,
		Email:        req.Email,
		PasswordHash: hashedPassword,
		Role:         "staff",
		IsVerified:   true,
		SocietyID:    &societyID,
	}
	if err := s.userRepo.Create(ctx, user); err != nil {
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to create staff user", http.StatusInternalServerError, err)
	}
	return user, nil
}
// ==================== QR / SELF-SERVICE PATH ====================

// GetSocietyFlatsByCode resolves the society by its code and returns its flats.
// This is a public-ish endpoint — the QR code only contains the society code, not an ID.
func (s *onboardingService) GetSocietyFlatsByCode(ctx context.Context, societyCode string) ([]*models.Flat, error) {
	ctx, cancel := context.WithTimeout(ctx, service.DefaultTimeout)
	defer cancel()

	society, err := s.societyRepo.GetSocietyByCode(ctx, societyCode)
	if err != nil {
		if errors.Is(err, repository.ErrSocietyNotFound) {
			return nil, models.NewAppError(models.ErrCodeNotFound, "society not found", http.StatusNotFound, nil)
		}
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to lookup society", http.StatusInternalServerError, err)
	}
	if !society.IsActive {
		return nil, models.NewAppError(models.ErrCodeForbidden, "society is not active", http.StatusForbidden, nil)
	}

	flats, err := s.flatRepo.GetFlatsBySocietyID(ctx, society.Id)
	if err != nil {
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to fetch flats", http.StatusInternalServerError, err)
	}
	return flats, nil
}

// SubmitClaim creates a pending FlatClaimRequest.
//
// Guards (in order):
//  1. Flat exists and belongs to the given society.
//  2. No other primary resident currently occupies the flat.
//  3. No duplicate pending claim from the same user for the same flat.
func (s *onboardingService) SubmitClaim(ctx context.Context, req *models.SubmitClaimRequest) (*models.FlatClaimRequest, error) {
	ctx, cancel := context.WithTimeout(ctx, service.DefaultTimeout)
	defer cancel()

	// Guard 1: flat must exist and belong to the society.
	flat, err := s.flatRepo.GetFlatByID(ctx, req.FlatID)
	if err != nil {
		if errors.Is(err, repository.ErrFlatNotFound) {
			return nil, models.NewAppError(models.ErrCodeNotFound, "flat not found", http.StatusNotFound, nil)
		}
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to fetch flat", http.StatusInternalServerError, err)
	}
	if flat.SocietyID != req.SocietyID {
		return nil, models.NewAppError(models.ErrCodeNotFound, "flat not found in this society", http.StatusNotFound, nil)
	}

	// Guard 2: flat must not already have a primary resident.
	primaryCount, err := s.userRepo.CountByFlatAndRole(ctx, req.FlatID, RolePrimaryResident)
	if err != nil {
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to check flat occupancy", http.StatusInternalServerError, err)
	}
	if primaryCount > 0 {
		return nil, models.NewAppError(models.ErrCodeConflict, "flat already has a primary resident", http.StatusConflict, ErrFlatAlreadyOccupied)
	}

	// Guard 3: no duplicate pending claim.
	existing, err := s.claimRepo.GetPendingClaimByUserAndFlat(ctx, req.UserID, req.FlatID)
	if err != nil && !errors.Is(err, repository.ErrClaimNotFound) {
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to check existing claims", http.StatusInternalServerError, err)
	}
	if existing != nil {
		return nil, models.NewAppError(models.ErrCodeConflict, "you already have a pending claim for this flat", http.StatusConflict, ErrDuplicatePendingClaim)
	}

	claim, err := s.claimRepo.CreateClaim(ctx, &models.FlatClaimRequest{
		UserID:    req.UserID,
		FlatID:    req.FlatID,
		SocietyID: req.SocietyID,
		Note:      req.Note,
	})
	if err != nil {
		if errors.Is(err, repository.ErrClaimAlreadyExists) {
			return nil, models.NewAppError(models.ErrCodeConflict, "you already have a pending claim for this flat", http.StatusConflict, err)
		}
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to submit claim", http.StatusInternalServerError, err)
	}
	return claim, nil
}

// ApproveClaim approves a claim and runs the full flat-assignment transaction:
//  1. Set user.flat_id + user.society_id + user.role = primary resident.
//  2. Set user.is_verified = true (activates the account).
//  3. Mark flat status = active (occupied) — flat was already active by default,
//     but this keeps the state machine explicit.
//  4. Revoke all pending invites for the same flat (no stale tokens).
func (s *onboardingService) ApproveClaim(ctx context.Context, req *models.ReviewClaimRequest) (*models.OnboardingResult, error) {
	ctx, cancel := context.WithTimeout(ctx, service.DefaultTimeout)
	defer cancel()

	// Load the claim first (outside TX — read-only).
	claim, err := s.claimRepo.GetClaimByID(ctx, req.ClaimID)
	if err != nil {
		if errors.Is(err, repository.ErrClaimNotFound) {
			return nil, models.NewAppError(models.ErrCodeNotFound, "claim not found", http.StatusNotFound, nil)
		}
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to fetch claim", http.StatusInternalServerError, err)
	}
	if !claim.IsPending() {
		return nil, models.NewAppError(models.ErrCodeConflict, "claim is no longer pending", http.StatusConflict, ErrClaimNotPending)
	}

	// Load the user and flat (outside TX — read-only).
	user, err := s.userRepo.GetByID(ctx, claim.UserID)
	if err != nil {
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to fetch claimant", http.StatusInternalServerError, err)
	}
	flat, err := s.flatRepo.GetFlatByID(ctx, claim.FlatID)
	if err != nil {
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to fetch flat", http.StatusInternalServerError, err)
	}

	// Double-check: still no primary resident (race condition guard).
	primaryCount, err := s.userRepo.CountByFlatAndRole(ctx, claim.FlatID, RolePrimaryResident)
	if err != nil {
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to check flat occupancy", http.StatusInternalServerError, err)
	}
	if primaryCount > 0 {
		return nil, models.NewAppError(models.ErrCodeConflict, "flat was assigned to another resident in the meantime", http.StatusConflict, ErrFlatAlreadyOccupied)
	}

	var updatedClaim *models.FlatClaimRequest

	txErr := s.txManager.WithTransaction(ctx, func(txCtx context.Context) error {
		// 1. Approve the claim row.
		approved, err := s.claimRepo.ApproveClaim(txCtx, req.ClaimID, req.ReviewerID)
		if err != nil {
			if errors.Is(err, repository.ErrClaimNotPending) {
				return models.NewAppError(models.ErrCodeConflict, "claim is no longer pending", http.StatusConflict, err)
			}
			return fmt.Errorf("onboarding: approve claim: %w", err)
		}
		updatedClaim = approved

		// 2. Assign user to society (role = primary resident).
		if err := s.userRepo.UpdateSocietyID(txCtx, user.ID, claim.SocietyID, RolePrimaryResident); err != nil {
			return fmt.Errorf("onboarding: assign society to user: %w", err)
		}

		// 3. Assign user to flat.
		if err := s.userRepo.UpdateFlatID(txCtx, user.ID, &claim.FlatID); err != nil {
			return fmt.Errorf("onboarding: assign flat to user: %w", err)
		}

		// 4. Activate the user account.
		if err := s.userRepo.UpdateIsVerified(txCtx, user.ID, true); err != nil {
			return fmt.Errorf("onboarding: activate user: %w", err)
		}

		// 5. Mark flat as active / occupied.
		if _, err := s.flatRepo.UpdateFlatStatus(txCtx, flat.ID, models.FlatStatusActive); err != nil {
			return fmt.Errorf("onboarding: update flat status: %w", err)
		}

		// 6. Revoke all outstanding invites for this flat (clean up stale tokens).
		if err := s.inviteRepo.RevokeAllInvitesByFlat(txCtx, flat.ID); err != nil {
			return fmt.Errorf("onboarding: revoke stale invites: %w", err)
		}

		return nil
	})
	if txErr != nil {
		var appErr *models.AppError
		if errors.As(txErr, &appErr) {
			return nil, appErr
		}
		return nil, models.NewAppError(models.ErrCodeTransactionFailed, "failed to approve claim", http.StatusInternalServerError, txErr)
	}

	// Re-fetch user to get the updated state.
	updatedUser, err := s.userRepo.GetByID(ctx, user.ID)
	if err != nil {
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to fetch updated user", http.StatusInternalServerError, err)
	}
	updatedFlat, err := s.flatRepo.GetFlatByID(ctx, flat.ID)
	if err != nil {
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to fetch updated flat", http.StatusInternalServerError, err)
	}

	return &models.OnboardingResult{
		User:    updatedUser.ToResponse(),
		Flat:    updatedFlat.ToResponse(),
		Claim:   updatedClaim,
		Message: "Claim approved. Resident has been activated and assigned to the flat.",
	}, nil
}

// RejectClaim sets the claim status to rejected and records the reason.
func (s *onboardingService) RejectClaim(ctx context.Context, req *models.ReviewClaimRequest) (*models.FlatClaimRequest, error) {
	ctx, cancel := context.WithTimeout(ctx, service.DefaultTimeout)
	defer cancel()

	claim, err := s.claimRepo.RejectClaim(ctx, req.ClaimID, req.ReviewerID, req.RejectionReason)
	if err != nil {
		if errors.Is(err, repository.ErrClaimNotPending) {
			return nil, models.NewAppError(models.ErrCodeConflict, "claim is no longer pending", http.StatusConflict, err)
		}
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to reject claim", http.StatusInternalServerError, err)
	}
	return claim, nil
}

// ==================== INVITE PATH ====================

// CreateInvite delegates to InviteService.
// Authorization (actor must be admin of this society or primary resident of
// this flat) is enforced at the handler layer via role/society guards.
func (s *onboardingService) CreateInvite(ctx context.Context, req inviteservice.CreateInviteRequest) (*inviteservice.InviteResponse, error) {
	return s.inviteSvc.CreateInvite(ctx, req)
}

// RedeemInvite validates the invite token and immediately assigns the user to
// the flat, setting their role and activating them — no admin approval needed.
//
// Assignment rules:
//   - invite created by admin    → user becomes primary resident of that flat
//   - invite created by resident → user becomes primary resident (family member)
//     unless the flat already has a primary resident, in which case we block
//
// The entire redemption (token increment + user assignment) runs in one TX.
func (s *onboardingService) RedeemInvite(ctx context.Context, req *models.RedeemInviteRequest) (*models.OnboardingResult, error) {
	ctx, cancel := context.WithTimeout(ctx, service.DefaultTimeout)
	defer cancel()

	// Load user.
	user, err := s.userRepo.GetByID(ctx, req.UserID)
	if err != nil {
		return nil, models.NewAppError(models.ErrCodeNotFound, "user not found", http.StatusNotFound, nil)
	}
	if user.FlatID != nil {
		return nil, models.NewAppError(models.ErrCodeConflict, "you are already assigned to a flat", http.StatusConflict, ErrUserAlreadyAssigned)
	}

	// Peek at the invite to perform pre-flight checks (outside TX).
	invite, err := s.inviteRepo.GetInviteByToken(ctx, req.Token)
	if err != nil {
		if errors.Is(err, repository.ErrInviteNotFound) {
			return nil, models.NewAppError(models.ErrCodeNotFound, "invite token is invalid", http.StatusNotFound, nil)
		}
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to look up invite", http.StatusInternalServerError, err)
	}
	if !invite.IsValid() {
		switch invite.Status() {
		case models.InviteStatusRevoked:
			return nil, models.NewAppError(models.ErrCodeForbidden, "this invite has been revoked", http.StatusForbidden, nil)
		case models.InviteStatusExpired:
			return nil, models.NewAppError(models.ErrCodeForbidden, "this invite has expired", http.StatusForbidden, nil)
		case models.InviteStatusExhausted:
			return nil, models.NewAppError(models.ErrCodeForbidden, "this invite has already been used", http.StatusForbidden, nil)
		default:
			return nil, models.NewAppError(models.ErrCodeForbidden, "this invite is no longer valid", http.StatusForbidden, nil)
		}
	}

	// Load the flat.
	flat, err := s.flatRepo.GetFlatByID(ctx, invite.FlatID)
	if err != nil {
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to fetch flat", http.StatusInternalServerError, err)
	}
	if flat.Status != models.FlatStatusActive {
		return nil, models.NewAppError(models.ErrCodeConflict, "flat is not available", http.StatusConflict, nil)
	}

	// Enforce single-primary-resident rule.
	primaryCount, err := s.userRepo.CountByFlatAndRole(ctx, flat.ID, RolePrimaryResident)
	if err != nil {
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to check flat occupancy", http.StatusInternalServerError, err)
	}
	if primaryCount > 0 {
		return nil, models.NewAppError(models.ErrCodeConflict, "flat already has a primary resident", http.StatusConflict, ErrFlatAlreadyOccupied)
	}

	var updatedUser *models.User

	txErr := s.txManager.WithTransaction(ctx, func(txCtx context.Context) error {
		// 1. Atomically increment used_count (validates token hasn't been raced).
		if err := s.inviteRepo.IncrementUsedCount(txCtx, invite.ID); err != nil {
			return fmt.Errorf("onboarding: increment invite used_count: %w", err)
		}

		// 2. Assign user to society, flat, and role in one go.
		if err := s.userRepo.UpdateSocietyID(txCtx, user.ID, flat.SocietyID, RolePrimaryResident); err != nil {
			return fmt.Errorf("onboarding: assign society to user: %w", err)
		}
		if err := s.userRepo.UpdateFlatID(txCtx, user.ID, &flat.ID); err != nil {
			return fmt.Errorf("onboarding: assign flat to user: %w", err)
		}

		// 3. Auto-activate the user (trust implied by invite).
		if err := s.userRepo.UpdateIsVerified(txCtx, user.ID, true); err != nil {
			return fmt.Errorf("onboarding: activate user: %w", err)
		}

		return nil
	})
	if txErr != nil {
		var appErr *models.AppError
		if errors.As(txErr, &appErr) {
			return nil, appErr
		}
		return nil, models.NewAppError(models.ErrCodeTransactionFailed, "failed to redeem invite", http.StatusInternalServerError, txErr)
	}

	// Re-fetch updated state.
	updatedUser, _ = s.userRepo.GetByID(ctx, user.ID)
	updatedFlat, _ := s.flatRepo.GetFlatByID(ctx, flat.ID)

	return &models.OnboardingResult{
		User:    updatedUser.ToResponse(),
		Flat:    updatedFlat.ToResponse(),
		Message: "Invite redeemed. You have been assigned to your flat and your account is now active.",
	}, nil
}

// ==================== ADMIN / READ-ONLY VIEWS ====================

func (s *onboardingService) ListPendingClaims(ctx context.Context, societyID int64) ([]*models.FlatClaimRequest, error) {
	ctx, cancel := context.WithTimeout(ctx, service.DefaultTimeout)
	defer cancel()
	status := models.ClaimStatusPending
	claims, err := s.claimRepo.GetClaimsBySociety(ctx, societyID, &status)
	
	if err != nil {
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to fetch pending claims", http.StatusInternalServerError, err)
	}
	return claims, nil
}

func (s *onboardingService) ListAllClaims(ctx context.Context, societyID int64, status *models.ClaimStatus) ([]*models.FlatClaimRequest, error) {
	ctx, cancel := context.WithTimeout(ctx, service.DefaultTimeout)
	defer cancel()
	claims, err := s.claimRepo.GetClaimsBySociety(ctx, societyID, status)
	if err != nil {
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to fetch claims", http.StatusInternalServerError, err)
	}
	return claims, nil
}

func (s *onboardingService) GetMyClaimHistory(ctx context.Context, userID int64) ([]*models.FlatClaimRequest, error) {
	ctx, cancel := context.WithTimeout(ctx, service.DefaultTimeout)
	defer cancel()
	claims, err := s.claimRepo.GetClaimsByUser(ctx, userID)
	if err != nil {
		return nil, models.NewAppError(models.ErrCodeDatabaseError, "failed to fetch claim history", http.StatusInternalServerError, err)
	}
	return claims, nil
}

func (s *onboardingService) GetActiveInvitesForFlat(ctx context.Context, flatID int64, societyID int64) ([]*models.FlatInvite, error) {
	return s.inviteSvc.GetActiveInvitesForFlat(ctx, flatID, societyID)
}

func (s *onboardingService) RevokeInvite(ctx context.Context, inviteID int64, actorID int64) error {
	return s.inviteSvc.RevokeInvite(ctx, inviteID, actorID)
}
